Repository timemates/sdk, pull requests merged in 2023-07, with the labels that each got.

#20 feat: dev & release workflow
  .github/workflows/publish-dev-version.yml
  .github/workflows/publish-release-version.yml
  build.gradle.kts
  gradle/libs.versions.toml
  grpc-engine/build.gradle.kts
  sdk/build.gradle.kts
Labels: feature, automation

#28 tests&feat: run tests on PR
  .github/workflows/run-tests
Labels: automation

#26 feat (#19): Get current user session
  grpc-engine/src/main/kotlin/io/timemates/api/grpc/GrpcTimeMatesRequestsEngine.kt
  grpc-engine/src/main/proto/io/timemates/api/timers/sessions/TimerSessionsService.proto
  grpc-engine/src/main/proto/io/timemates/api/timers/sessions/requests/GetUserCurrentSessionRequest.proto
  sdk/src/commonMain/kotlin/io/timemates/sdk/timers/sessions/TimersSessionsApi.kt
  sdk/src/commonMain/kotlin/io/timemates/sdk/timers/sessions/requests/GetUserCurrentSessionRequest.kt
Labels: feature

#31 feat (#30): Configure new account API
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  grpc-engine/src/main/kotlin/io/timemates/api/grpc/internal/ResultExt.kt
  sdk/src/commonMain/kotlin/io/timemates/sdk/authorization/email/EmailAuthorizationApi.kt
Labels: feature

#33 feat (#32): `getTimerState` API method
  grpc-engine/src/main/kotlin/io/timemates/api/grpc/GrpcTimeMatesRequestsEngine.kt
  grpc-engine/src/main/kotlin/io/timemates/api/grpc/mappers/TimersMapper.kt
  sdk/src/commonMain/kotlin/io/timemates/sdk/timers/sessions/TimersSessionsApi.kt
  sdk/src/commonMain/kotlin/io/timemates/sdk/timers/sessions/requests/GetTimerStateRequest.kt
  sdk/src/commonMain/kotlin/io/timemates/sdk/timers/types/Timer.kt
Labels: feature

#36 feat (#35): `PagesIterator<T>.map` is added
  sdk/src/commonMain/kotlin/io/timemates/sdk/common/pagination/PagesIterator.kt
Labels: feature

#37 feat: propagate `Result<T>` in `PagesIterator<T>`
  sdk/src/commonMain/kotlin/io/timemates/sdk/common/pagination/PagesIterator.kt
Labels: feature

#40 feat (#39): `sessions` are now available under `TimersApi`
  sdk/src/commonMain/kotlin/io/timemates/sdk/timers/TimersApi.kt
Labels: invalid

#41 fix: jdk version on `publish-release-version` workflow
  .github/workflows/publish-release-version.yml
Labels: automation
